### PR TITLE
Organize/stylize code and docs

### PR DESCRIPTION
**Pull request by MillironX**
So, I usually don't like "code organization" PRs, but I think this is long overdue to make SequenceVariation feel and function as a proper package, rather than a side project. The basic jist:

- Move code into files by type
- Add formatting guidelines
- Clearly mark public/private API using Blue style conventions and docs
- Add docstrings and tutorials
- Refine CI testing workflows

Defining the API also required breaking it. I am planning two more PRs in quick succession to this one before tagging a new release.

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/v1/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [x] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Review by kescobo — APPROVED** [review]
This is phenomenal, thank you! I mostly skimmed just now - I can take a deeper look if you think that would be helpful, but I'm all for it!

One thing that might be helpful, especially since there's so much new documentation, would be to get preview builds working. Right now, it's being blocked by this: 
image

... which is annoying. I think there's a way to change the options, but I can't recall what it is. Let me know if there's something I can change at the repo level, or if you need write access so that you can push your branch direct to this repo rather than from your fork.

**Comment by MillironX** [comment]
> One thing that might be helpful, especially since there's so much new documentation, would be to get preview builds working. 

Agreed!

> I think there's a way to change the options, but I can't recall what it is. 

I think it's usually adding `push_preview=true` to make.jl, but that's already set.

https://github.com/BioJulia/SequenceVariation.jl/blob/73d2781ee945ebc64f6b5599ef0838f4cab585e9/docs/make.jl#L18-L22

> Let me know if there's something I can change at the repo level, or if you need write access so that you can push your branch direct to this repo rather than from your fork.

Thanks. I do already have write access. The reason I work on my own fork is that I've always considered branches of the upstream repository to be an anti-pattern; but documentation builds are a worthy reason to break my crusty old-fashioned notions of "correctness." :wink:

**Comment by kescobo** [comment]
>I think it's usually adding push_preview=true to make.jl, but that's already set.

Yeah - that bit I screen-shot is the part of the docs build that's trying to deploy the preview.

> The reason I work on my own fork is that I've always considered branches of the upstream repository to be an anti-pattern; 

I agree with this 100%. And I think there's some repository setting that can allow this - it has something to do with having access to the DOCUMENTER_KEY or something... I'll ask on slack to see, I'm pretty sure I've dealt with it in the past...

**Comment by kescobo** [comment]
Hmm - just looked at the docs, apparently I'm wrong: 
image

**Comment by CiaranOMara** [comment]
> The reason I work on my own fork is that I've always considered branches of the upstream repository to be an anti-pattern; but documentation builds are a worthy reason to break my crusty old-fashioned notions of "correctness." wink

We're limited by the tools we've got. Before a feature release or anything more significant, I prefer setting up a release branch. I am okay with having that branch in the main repository, as it signals intent and allows everybody involved to have their say and catch issues. At the very least, it will enable people to preview new documentation. As an aside, many of my release branches only have one commit that increments the project version.

**Pull request merged**
